### ISSUE TITLE
Softvector Build Fails on Mac and Windows

### ISSUE THREAD

**Issue by fpedd** [tum-ei-eda/softvector#7]
The [softvector build](https://github.com/tum-ei-eda/etiss/pull/76) on Mac, more specifically the linking, fails for some reason. The build for Linux appears to work just fine (until it gets stopped by the failing Mac build). The linker is having a hard time finding some symbols:

```
[ 91%] Linking CXX shared library libetiss_softvector.dylib
Undefined symbols for architecture x86_64:
  "VLSU::load_eew(std::__1::function<void (unsigned long, unsigned char*, unsigned long)>, unsigned char*, unsigned long long, unsigned long long, unsigned short, unsigned short, unsigned short, unsigned short, unsigned long long, unsigned short, unsigned char, short)", referenced from:
      _etiss_vload_encoded_unitstride in etiss_softvector.cpp.o
      _etiss_vload_encoded_stride in etiss_softvector.cpp.o
      _etiss_vload_segment_unitstride in etiss_softvector.cpp.o
      _etiss_vload_segment_stride in etiss_softvector.cpp.o
  "VLSU::store_eew(std::__1::function<void (unsigned long, unsigned char*, unsigned long)>, unsigned char*, unsigned long long, unsigned long long, unsigned short, unsigned short, unsigned short, unsigned short, unsigned long long, unsigned short, unsigned char, short)", referenced from:
      _etiss_vstore_encoded_unitstride in etiss_softvector.cpp.o
      _etiss_vstore_encoded_stride in etiss_softvector.cpp.o
      _etiss_vstore_segment_unitstride in etiss_softvector.cpp.o
      _etiss_vstore_segment_stride in etiss_softvector.cpp.o
  "VTYPE::decode(unsigned short, unsigned char*, unsigned char*, unsigned int*, unsigned char*, unsigned char*)", referenced from:
      _etiss_vload_encoded_unitstride in etiss_softvector.cpp.o
      _etiss_vload_encoded_stride in etiss_softvector.cpp.o
      _etiss_vload_segment_unitstride in etiss_softvector.cpp.o
      _etiss_vload_segment_stride in etiss_softvector.cpp.o
      _etiss_vstore_encoded_unitstride in etiss_softvector.cpp.o
      _etiss_vstore_encoded_stride in etiss_softvector.cpp.o
      _etiss_vstore_segment_unitstride in etiss_softvector.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/jitlibs/softvector/libetiss_softvector.dylib] Error 1
make[1]: *** [src/jitlibs/softvector/CMakeFiles/etiss_softvector.dir/all] Error 2
make: *** [all] Error 2
Error: Process completed with exit code 2.
``` 

EDIT: The windows build appears to be failing as well (sorry for the confusion).

**Comment by rafzi** [comment]
I'm pretty sure this is the issue:

https://github.com/fabianpedd/etiss/blob/fabianpedd-vector/src/jitlibs/softvector/CMakeLists.txt#L36

INTERFACE does not link the specified libraries to the target.

https://cmake.org/cmake/help/latest/command/target_link_libraries.html#libraries-for-a-target-and-or-its-dependents

And since your target is SHARED, it does require linking, except on linux. `.so` shared libs can resolve undefined symbols at runtime, but `.dll` and `.dylib` can not.

Changing the link mode to PUBLIC should resolve this.

**Comment by fpedd** [comment]
@rafzi thanks, that fixed that issue.

The windows build appears to be failing as well. Apparently, Softvector uses "alternative tokens" for logical operators, for example [here](https://github.com/tum-ei-eda/softvector/blob/efd84171ee2d2cd6d04ac6629b196aac9e62b818/src/vpu/softvector-vector.cpp#L330) and [here](https://github.com/tum-ei-eda/softvector/blob/efd84171ee2d2cd6d04ac6629b196aac9e62b818/src/vpu/softvector-register.cpp#L47). According to [this](https://stackoverflow.com/questions/24414124/why-does-vs-not-define-the-alternative-tokens-for-logical-operators) the MSVC compiler is actually nonconforming with default compilation settings and does not support them. So one solution would be to force the compiler to conformatiy with `/permissive-` or `/Za`, or include the `<ciso646>` header.

However, since Softvector is also using the "primary tokes" at [other places](https://github.com/tum-ei-eda/softvector/blob/efd84171ee2d2cd6d04ac6629b196aac9e62b818/include/vpu/softvector-types.hpp#L234), I would just recommend switching to primary tokes altogether.

**Comment by rafzi** [comment]
I like the primary tokens more, because they are way more common.

Still, `/permissive-` is a healthy flag to have. We should try if etiss compiles with it.
